//Model
const model = {
	//app
	app: {
		currentUser: '', 
		currentPage: "logIn",
		disable: "disabled",
		userIndex: null,
	},
	//inputs
	login: {
		userName: "",
		pwd: "",
	},
	newUser: {
		userName: '',
		firstName: '',
		lastName: '',
		pwd: '',
		confirmPwd: '',
		isAdmin: false,
	},
	overView: {
		selectedDate: "",
		selectedDay: "",
		selectedId: null,
		selectedUserId: null,
	},
	newExperience: {
		id: "",
		feelings: [], 
		triggers: [],
		location: "",
		comments: [],
		time: "",
		date: "",
		day: "",
		weekId: 1,
	},
	//data
	feelings: [
		{ name: "Glad", subFeels: [
			{ name: 'Spent'},
			{ name: 'Attraktiv'},
			{ name: 'Energisk'},
			{ name: 'Leken'},
			{ name: 'Kreativ'},
			{ name: 'Oppmerksom'},
		], 
	},
		{ name: "Trist", subFeels: [
			{name: 'Skyldig',},
			{name: 'Skamfull',},
			{name: 'Deprimert',},
			{name: 'Ensom',},
			{name: 'Kjedelig',},
			{name: 'Trøtt',},
		],
	},
		{ name: "Sint", subFeels: [
			{ name: 'Frustrert',},
			{ name: 'Rasende',},
			{ name: 'Fiendtlig',},
			{ name: 'Såret',},
			{ name: 'Hatefull',},
			{ name: 'Kritisk',},
		], 
	},
		{ name: "Sterk", subFeels: 
		[
			{name: 'Trofast', },
			{name: 'Viktig',},
			{name: 'Håpefull',},
			{name: 'Verdsatt',},
			{name: 'Respektert',},
			{name: 'Stolt',},
		], 
	},	
		{ name: "Rolig", subFeels: 
		[
			{name: 'Tilfreds',},
			{name: 'Intim',},
			{name: 'Kjærlig',},
			{name: 'Tillitsfull',},
			{name: 'Oppbygget',},
		], 
	},
		{ name: "Redd", subFeels: 
			[
			{name: 'Avvist', },
			{name: 'Forvirret',},
			{name: 'Hjelpesløs',},
			{name: 'Føyelig', },
			{name: 'Utrygg',},
			{name: 'Engstelig', },
			], 
	},
	],
	locations: [
		{ name: "Hjemme" },
		{ name: "Jobb" },
		{ name: "Butikk" },
		{ name: "Transport" },
		{ name: "Aktivitet" },
		{ name: "Annet" },
	],
	triggers: [
		{ name: "Møte" },
		{ name: "Syn" },
		{ name: "Berøring" },
		{ name: "Hørsel" },
		{ name: "Smak" },
		{ name: "Lukt" },
		{ name: "Tanke" },
		{ name: "Vet ikke" },
	],
	hensiktApp: "Øk bevissthet rundt dine følelsesmessige mønstre og reaksjoner. <br>Informasjonen som du samler om dine følelser og mestringsstrategier gir grunnlag for refleskjonsamtale med din veileder",
	users: [],
	challenges: [],
	experiences: [],
	chat: [],
};